apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: otto-cyprien
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cyprienotto/backend:0.0.1
          ports:
            - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: otto-cyprien
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
