apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rabbit-receiver-hpa
  namespace: otto-cyprien
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbit-receiver
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
